sudo: required
services:
  - docker
before_install:
  - docker build --no-cache -t mstackio/alpine:latest .
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mstackio/alpine:latest
